parameters:
#    cabinet.example.class: Tryout\CabinetBundle\Example

services:
#    cabinet.example:
#        class: %cabinet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
